
networks:
  network1:
    name: kafka-network-manual # docker network create -d bridge kafka-network-manual
    external: true

services:

  mm2-bidirect:
    image: confluentinc/cp-kafka
    hostname: mm2-bidirect
    container_name: mm2-bidirect
    networks:
      - network1
    volumes:
      - ./bi_config:/tmp/kafka/config
    ports:
      - 9096:9096
      - 29096:29096
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_ZOOKEEPER_CONNECT: zookeeperA:22181,zookeeperB:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29096,PLAINTEXT_HOST://:9096
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://mm2-bidirect:29096,PLAINTEXT_HOST://localhost:9096
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_AUTO_OFFSET_RESET: "latest"
